Update to use intel/linux-lts 6.12.24

diff --git a/gen-config b/gen-config
--- a/gen-config
+++ b/gen-config
@@ -20,21 +20,22 @@ set -eu -o pipefail
 linux_merge_config="./scripts/kconfig/merge_config.sh"
 make_opts=""
 
+ls -d ../linux-intel-lts/scripts 1>&2
 if [ -n "${LINUX_UPSTREAM_VERSION:-}" ]; then
-    linux_merge_config="../linux-$LINUX_UPSTREAM_VERSION/scripts/kconfig/merge_config.sh"
-    make_opts="-C ../linux-$LINUX_UPSTREAM_VERSION O=$PWD"
+  linux_merge_config="../linux-intel-lts/scripts/kconfig/merge_config.sh"
+  make_opts="-C ../linux-intel-lts O=$PWD"
 fi
 
 if [ -z "$linux_merge_config" ]; then
-    printf 'Error: Could not find merge_config.sh from the linux source tree!\n'
-    exit 1
+  printf 'Error: Could not find merge_config.sh from the linux source tree!\n'
+  exit 1
 fi
 
 sed_config_exp='s/^\(# \)\{0,1\}\(CONFIG_[a-zA-Z0-9_]*\)[= ].*/\2/p'
 
 if [ $# -ne 2 ]; then
-    printf 'Usage: gen-config base.config local.config\n'
-    exit 1
+  printf 'Usage: gen-config base.config local.config\n'
+  exit 1
 fi
 
 base_config="$1"
@@ -48,12 +49,12 @@ make $make_opts KCONFIG_ALLCONFIG=.config alldefconfig
 
 rc=0
 for cfg in $(sed -n "$sed_config_exp" "$local_config.gen"); do
-    requested="$(grep -w "$cfg" "$local_config.gen" || true)"
-    actual="$(grep -w "$cfg" .config || true)"
-    if [ "$requested" != "$actual" ]; then
-        printf 'Local config setting for %s didn'\''t make it into the final config\n' "$cfg"
-        rc=1
-    fi
+  requested="$(grep -w "$cfg" "$local_config.gen" || true)"
+  actual="$(grep -w "$cfg" .config || true)"
+  if [ "$requested" != "$actual" ]; then
+    printf 'Local config setting for %s didn'\''t make it into the final config\n' "$cfg"
+    rc=1
+  fi
 done
 
 rm "$local_config.gen"
